// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package uy.com.s4b.webservice;


public class ArrayOfLocalizadorBoletinesInfo {
    protected uy.com.s4b.webservice.LocalizadorBoletinesInfo[] localizadorBoletinesInfo;
    
    public ArrayOfLocalizadorBoletinesInfo() {
    }
    
    public ArrayOfLocalizadorBoletinesInfo(uy.com.s4b.webservice.LocalizadorBoletinesInfo[] localizadorBoletinesInfo) {
        this.localizadorBoletinesInfo = localizadorBoletinesInfo;
    }
    
    public uy.com.s4b.webservice.LocalizadorBoletinesInfo[] getLocalizadorBoletinesInfo() {
        return localizadorBoletinesInfo;
    }
    
    public void setLocalizadorBoletinesInfo(uy.com.s4b.webservice.LocalizadorBoletinesInfo[] localizadorBoletinesInfo) {
        this.localizadorBoletinesInfo = localizadorBoletinesInfo;
    }
}
