// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package uy.com.s4b.webservice;


public class EncryptDataResponse {
    protected java.lang.String encryptDataResult;
    
    public EncryptDataResponse() {
    }
    
    public EncryptDataResponse(java.lang.String encryptDataResult) {
        this.encryptDataResult = encryptDataResult;
    }
    
    public java.lang.String getEncryptDataResult() {
        return encryptDataResult;
    }
    
    public void setEncryptDataResult(java.lang.String encryptDataResult) {
        this.encryptDataResult = encryptDataResult;
    }
}
