// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package uy.com.s4b.webservice;


public class EncryptData {
    protected java.lang.String username;
    protected java.lang.String password;
    protected java.lang.String unEncryptedData;
    protected java.lang.String key;
    
    public EncryptData() {
    }
    
    public EncryptData(java.lang.String username, java.lang.String password, java.lang.String unEncryptedData, java.lang.String key) {
        this.username = username;
        this.password = password;
        this.unEncryptedData = unEncryptedData;
        this.key = key;
    }
    
    public java.lang.String getUsername() {
        return username;
    }
    
    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getUnEncryptedData() {
        return unEncryptedData;
    }
    
    public void setUnEncryptedData(java.lang.String unEncryptedData) {
        this.unEncryptedData = unEncryptedData;
    }
    
    public java.lang.String getKey() {
        return key;
    }
    
    public void setKey(java.lang.String key) {
        this.key = key;
    }
}
