// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package uy.com.s4b.webservice;


public class GrabaDatosResponse {
    protected uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo grabaDatosResult;
    
    public GrabaDatosResponse() {
    }
    
    public GrabaDatosResponse(uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo grabaDatosResult) {
        this.grabaDatosResult = grabaDatosResult;
    }
    
    public uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo getGrabaDatosResult() {
        return grabaDatosResult;
    }
    
    public void setGrabaDatosResult(uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo grabaDatosResult) {
        this.grabaDatosResult = grabaDatosResult;
    }
}
