// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package uy.com.s4b.webservice;


public class LeeBoletin {
    protected java.lang.String username;
    protected java.lang.String password;
    protected java.lang.String DNI;
    protected java.lang.String matricula;
    
    public LeeBoletin() {
    }
    
    public LeeBoletin(java.lang.String username, java.lang.String password, java.lang.String DNI, java.lang.String matricula) {
        this.username = username;
        this.password = password;
        this.DNI = DNI;
        this.matricula = matricula;
    }
    
    public java.lang.String getUsername() {
        return username;
    }
    
    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getDNI() {
        return DNI;
    }
    
    public void setDNI(java.lang.String DNI) {
        this.DNI = DNI;
    }
    
    public java.lang.String getMatricula() {
        return matricula;
    }
    
    public void setMatricula(java.lang.String matricula) {
        this.matricula = matricula;
    }
}
