// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package uy.com.s4b.webservice;


public class LeeBoletinResponse {
    protected uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo leeBoletinResult;
    
    public LeeBoletinResponse() {
    }
    
    public LeeBoletinResponse(uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo leeBoletinResult) {
        this.leeBoletinResult = leeBoletinResult;
    }
    
    public uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo getLeeBoletinResult() {
        return leeBoletinResult;
    }
    
    public void setLeeBoletinResult(uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo leeBoletinResult) {
        this.leeBoletinResult = leeBoletinResult;
    }
}
