// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package uy.com.s4b.webservice;


public class LocalizadorBoletinesInfo {
    protected java.lang.String resultado;
    protected java.lang.String codigo;
    protected int boletinID;
    protected java.lang.String fechaInfraccion;
    protected java.lang.String DNI;
    protected java.lang.String matricula;
    protected java.lang.String puntos;
    protected java.lang.String importeSancion;
    protected java.lang.String recurrible;
    
    public LocalizadorBoletinesInfo() {
    }
    
    public LocalizadorBoletinesInfo(java.lang.String resultado, java.lang.String codigo, int boletinID, java.lang.String fechaInfraccion, java.lang.String DNI, java.lang.String matricula, java.lang.String puntos, java.lang.String importeSancion, java.lang.String recurrible) {
        this.resultado = resultado;
        this.codigo = codigo;
        this.boletinID = boletinID;
        this.fechaInfraccion = fechaInfraccion;
        this.DNI = DNI;
        this.matricula = matricula;
        this.puntos = puntos;
        this.importeSancion = importeSancion;
        this.recurrible = recurrible;
    }
    
    public java.lang.String getResultado() {
        return resultado;
    }
    
    public void setResultado(java.lang.String resultado) {
        this.resultado = resultado;
    }
    
    public java.lang.String getCodigo() {
        return codigo;
    }
    
    public void setCodigo(java.lang.String codigo) {
        this.codigo = codigo;
    }
    
    public int getBoletinID() {
        return boletinID;
    }
    
    public void setBoletinID(int boletinID) {
        this.boletinID = boletinID;
    }
    
    public java.lang.String getFechaInfraccion() {
        return fechaInfraccion;
    }
    
    public void setFechaInfraccion(java.lang.String fechaInfraccion) {
        this.fechaInfraccion = fechaInfraccion;
    }
    
    public java.lang.String getDNI() {
        return DNI;
    }
    
    public void setDNI(java.lang.String DNI) {
        this.DNI = DNI;
    }
    
    public java.lang.String getMatricula() {
        return matricula;
    }
    
    public void setMatricula(java.lang.String matricula) {
        this.matricula = matricula;
    }
    
    public java.lang.String getPuntos() {
        return puntos;
    }
    
    public void setPuntos(java.lang.String puntos) {
        this.puntos = puntos;
    }
    
    public java.lang.String getImporteSancion() {
        return importeSancion;
    }
    
    public void setImporteSancion(java.lang.String importeSancion) {
        this.importeSancion = importeSancion;
    }
    
    public java.lang.String getRecurrible() {
        return recurrible;
    }
    
    public void setRecurrible(java.lang.String recurrible) {
        this.recurrible = recurrible;
    }
}
