// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package uy.com.s4b.webservice;


public class UnEncryptDataResponse {
    protected java.lang.String unEncryptDataResult;
    
    public UnEncryptDataResponse() {
    }
    
    public UnEncryptDataResponse(java.lang.String unEncryptDataResult) {
        this.unEncryptDataResult = unEncryptDataResult;
    }
    
    public java.lang.String getUnEncryptDataResult() {
        return unEncryptDataResult;
    }
    
    public void setUnEncryptDataResult(java.lang.String unEncryptDataResult) {
        this.unEncryptDataResult = unEncryptDataResult;
    }
}
