// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package uy.com.s4b.webservice;


public class UnEncryptData {
    protected java.lang.String username;
    protected java.lang.String password;
    protected java.lang.String encryptedData;
    protected java.lang.String key;
    
    public UnEncryptData() {
    }
    
    public UnEncryptData(java.lang.String username, java.lang.String password, java.lang.String encryptedData, java.lang.String key) {
        this.username = username;
        this.password = password;
        this.encryptedData = encryptedData;
        this.key = key;
    }
    
    public java.lang.String getUsername() {
        return username;
    }
    
    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getEncryptedData() {
        return encryptedData;
    }
    
    public void setEncryptedData(java.lang.String encryptedData) {
        this.encryptedData = encryptedData;
    }
    
    public java.lang.String getKey() {
        return key;
    }
    
    public void setKey(java.lang.String key) {
        this.key = key;
    }
}
