// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package uy.com.s4b.webservice;

public interface WebServiceSoap extends java.rmi.Remote {
	public java.lang.String encryptData(java.lang.String username, java.lang.String password, java.lang.String unEncryptedData, java.lang.String key) throws java.rmi.RemoteException;

	public java.lang.String unEncryptData(java.lang.String username, java.lang.String password, java.lang.String encryptedData, java.lang.String key) throws java.rmi.RemoteException;

	public uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo leeBoletin(java.lang.String username, java.lang.String password, java.lang.String DNI, java.lang.String matricula) throws java.rmi.RemoteException;

	public uy.com.s4b.webservice.ArrayOfLocalizadorBoletinesInfo grabaDatos(java.lang.String username, java.lang.String password, java.lang.String DNI, java.lang.String matricula, java.lang.String email, java.lang.String matricula2, java.lang.String telefono, int tieneMultas, int tieneMultasRecurribles, int condiciones, int informacion, int origen) throws java.rmi.RemoteException;

}
